all:
	-del *.cached
	cd Controls
	make
	cd ..\Dialogs
	make
#	cd ..\Display
	make
	cd ..\Dnd
	make
	cd ..\EventDemo
	make
	cd ..\Font
	make
	cd ..\Grid
	make
	cd ..\HTML
	make
	cd ..\HtmlHelp
	make
	cd ..\HtmlListBox
	make
	cd ..\Internat
	make
	cd ..\Launcher
	make
	cd ..\ListCtrl
	make
	cd ..\ListView
	make
	cd ..\Listbook
	make
	cd ..\Mdi
	make
	cd ..\Minimal
	make
	cd ..\Notebook
	make
	cd ..\Printing
	make
	cd ..\SashWindow
	make
	cd ..\Splitter
	make
	cd ..\TreeCtrl
	make
#	cd ..\Tutorial
	make
	cd ..\Wizard
	make
	cd ..\Xrc
	make
	cd ..

clean:
	cd Controls
	make clean
	cd ..\Dialogs
	make clean
	cd ..\Display
	make clean
	cd ..\Dnd
	make clean
	cd ..\EventDemo
	make clean
	cd ..\Font
	make clean
	cd ..\Grid
	make clean
	cd ..\HTML
	make clean
	cd ..\HtmlHelp
	make clean
	cd ..\HtmlListBox
	make clean
	cd ..\Internat
	make clean
	cd ..\Launcher
	make clean
	cd ..\ListCtrl
	make clean
	cd ..\ListView
	make clean
	cd ..\Listbook
	make clean
	cd ..\Mdi
	make clean
	cd ..\Minimal
	make clean
	cd ..\Notebook
	make clean
	cd ..\Printing
	make clean
	cd ..\SashWindow
	make clean
	cd ..\Splitter
	make clean
	cd ..\TreeCtrl
	make clean
	cd ..\Tutorial
	make clean
	cd ..\Wizard
	make clean
	cd ..\Xrc
	make clean
	cd ..

